### ISSUE TITLE
Compilation on rpi / arm

### ISSUE THREAD

**Issue by Consti10** [ultravideo/uvgRTP#175]
Getting
`/home/openhd/uvgRTP/src/media_stream.cc: In member function ‘rtp_error_t uvgrtp::media_stream::configure_ctx(int, ssize_t)’:
/home/openhd/uvgRTP/src/media_stream.cc:615:42: error: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘ssize_t’ {aka ‘int’} [-Werror=sign-compare]
  615 |             if (value <= 0 || UINT32_MAX < value)
      |                                          ^
`
Removing -Werror in CMakeLists.txt obviosly fixes this.

I'd recommend removing -Werror, it can be quite a bitch with different compilers, on x86 this is no issue though.

**Comment by jrsnen** [comment]
I tried to fix the warning shown in 792b97d68c2e8c2c40c475fbebf720a1d0f8b9a8.

I'm a little hesitant to remove `-Werror` now that we have gotten uvgRTP to be warning free, since it is often easier to have zero tolerance for warnings than to remove them occasionally. Nevertheless, I would be ok removing it on some platforms/compilers though if there was a reason and a simple method.
