### ISSUE TITLE
RTCP interval issues

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#195]
Two problems: 
1. set_rtcp_interval_ms function does nothing because after setting it the stored value is never read
2.  Stream with one participant (my case) creates rtcp interval that is ridiculously small. Because of that, APP packets are not sent and just accumulate.

**Comment by tampsa** [comment]
Hey,

1. This is an internal function that is not supposed to be used. It probably will be removed. Please refer to the public API: https://ultravideo.github.io/uvgRTP/html/classuvgrtp_1_1rtcp.html

2. How small is ridiculously small? Which method are you using to send APP packets, hooking or send_app_packet()? It is supposed to work so that every time an RTCP compound packet is sent, also a single APP packet is also sent.

With this info we can take a deeper look at the problem.

**Comment by jrsnen** [comment]
I'm assuming this was the same issue as #197. Closing
