### ISSUE TITLE
Does uvgRTP handle RTP timestamp rotation correctly?

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#31]
Just curious. This can occur with really long streams and should work.

**Comment by altonen** [comment]
I don't see why not but I'm not sure if I've ever taken a video call long enough for this to happen. Easiest way to test this would be to increase the clock rate for HEVC to some very large number, recompile uvgRTP, start a video call with Kvazzup and observe what happens.

One issue that I started working before my departure was to implement a simple garbage collection for those frames which are not returned to user. Currently, uvgRTP does not free the memory of incomplete frames as each call to `uvgrtp::formats::*::packet_handler` only deals with active frame's frame buffer. LRU cache could be used to track the frames which are incomplete and late, and each call to the packet handler could free one incomplete frame's memory.

**Comment by polusto** [comment]
The rotation happens after 13 hours of video so it is not a very hard to imagine a scenario where this happens. Testing a 13 hour call is also not difficult, but it is not the most critical problem in uvgRTP at the moment.

I have a hard time imagining that something like timestamp differences work correctly in case of rotation if no attention is paid to it.

Can you make an issue of each unfinished task you are aware of?

**Comment by altonen** [comment]
Yes but if you increase the clock rate for HEVC to a much higher number, the timestamp increments are much larger and thus the wrap-around happens faster.

Another, even easier way to test whether they work is to use custom timestamps and reuse the values, i.e., not update them after each call or use small modulo for the timestamps such as 100 with a timestamp increment of 1 and observe what happens when the values wrap around.

I can create tickets for unsolved issues at some point.

**Comment by jrsnen** [comment]
I tested this by increasing the clock rate to 10% of UINT32 max. Did not find any issues.
