### ISSUE TITLE
APP packet name length

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#58]
Hello, 

there is a problem with the names of the APP packets. API guide states the following:
![image](https://user-images.githubusercontent.com/70014877/125683417-e317357b-7542-45d4-a5c7-4c7d01d69ec6.png)

When in fact, any name that is longer than 3 characters results in name corruption. For example, a packet named "123" produces:
![image](https://user-images.githubusercontent.com/70014877/125683807-2e0c3f93-a489-4900-b8ce-e36fbc95ccdb.png)

whereas packet named "1234" produces:
![image](https://user-images.githubusercontent.com/70014877/125685009-c9229fae-1a8a-44b9-9b46-e71f7530461d.png)

In the rtcp_app_packet declaration the name is represented as 
![image](https://user-images.githubusercontent.com/70014877/125684262-e1025012-44ce-4d0b-8a62-e0fabeeffbde.png)

So it is converted to an array with a length of [4] and is probably null-terminated, because the function takes char pointer 
```cpp
 rtp_error_t send_app_packet(char *name, uint8_t subtype, size_t payload_len, uint8_t *payload);
```
So I guess this is the intended behaviour with a misleading API guide. But I think that 3 characters long names are a bit short. 
Either the API should be fixed, or the names allowed to be longer, API fix is easier tho :)

p.s also when converting the name from the app packet that we receive back to char*, it becomes non null-terminated.

**Comment by polusto** [comment]
> 
> 
> Hello,
> 
> there is a problem with the names of the APP packets. API guide states the following:
> ![image](https://user-images.githubusercontent.com/70014877/125683417-e317357b-7542-45d4-a5c7-4c7d01d69ec6.png)
> 
> When in fact, any name that is longer than 3 characters results in name corruption. For example, a packet named "123" produces:
> ![image](https://user-images.githubusercontent.com/70014877/125683807-2e0c3f93-a489-4900-b8ce-e36fbc95ccdb.png)
> 
> whereas packet named "1234" produces:
> ![image](https://user-images.githubusercontent.com/70014877/125685009-c9229fae-1a8a-44b9-9b46-e71f7530461d.png)
> 
> In the rtcp_app_packet declaration the name is represented as
> ![image](https://user-images.githubusercontent.com/70014877/125684262-e1025012-44ce-4d0b-8a62-e0fabeeffbde.png)
> 
> So it is converted to an array with a length of [4] and is probably null-terminated, because the function takes char pointer
> 


I'm actually not convinced there is a problem. When looking at the spec (RFC 3550), 4 is the correct length for the name
![image](https://user-images.githubusercontent.com/6498638/125764778-90328f58-a279-4ce6-a352-1df18f5430f8.png)

Then, when looking at the name 
![image](https://user-images.githubusercontent.com/6498638/125764841-6bc719f5-b0f1-41a6-a18e-b6eda9c07a21.png)

I get the impression that you are supposed to use all 4 bytes for your name and not less. How uvgRTP handles this is just assume there are 4 characters there and copies them (this could probably be handled better, but it works in context of the specification.) This means that 123 will have the null-termination even though it is not supposed to have it. In case of 1234, it is copied without the null-termination, but this is actually correct, since the termination is not supposed to be there. In other words, when printing the name, you should not assume it is null-terminated, because it is not supposed to be.

> ```c++
>  rtp_error_t send_app_packet(char *name, uint8_t subtype, size_t payload_len, uint8_t *payload);
> ```

You are right, that the char* in the API is a misleading. (I vote for handling this with the C++ API at some point).

> 
> So I guess this is the intended behaviour with a misleading API guide. But I think that 3 characters long names are a bit short.
> Either the API should be fixed, or the names allowed to be longer, API fix is easier tho :)
> 

The length is specified by the RFC, so it cannot be increased. The API should probably be improved in some way.

> p.s also when converting the name from the app packet that we receive back to char*, it becomes non null-terminated.

I'm not super familiar with C, but maybe you should use a conversion function that adds the null-termination.
