### ISSUE TITLE
Refactoring examples into working code

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#61]
Currently, the examples only show the commands needed to use uvgRTP. The examples themselves don't work when run and I think it would be a better demonstration if they could actually be run and they would do something. This would also enable their usage in automated testing.

**Comment by polusto** [comment]
I've started working on this issue. You can follow the progress here: https://github.com/ultravideo/uvgRTP/tree/example_improvements

**Comment by altonen** [comment]
I have to say that I disagree with this change wholeheartedly. The point of the example was exactly that, showcasing the API, not to provide full-fledged, end-to-end example applications.

The idea I had was to provide more like a collection of very simple, read-only like example codes that users of uvgRTP could then incorporate into their own code. Now there is a lot of "unnecessary" churn to provide more application-type examples which I think is the wrong direction from end-user perspective. From a CI perspective it may be warranted by at least I did not enjoy reading some of them because now there's a lot of "unnecessary boilerplate".

Now the example codes look more like LIVE555's example code which I think are not that good either.

**Comment by polusto** [comment]
@altonen Which part of the example modification do you disagree? I've tried to do the following for the code:

1. Define values at the beginning. This is what they taught me in coding class and I think it makes the code more readable and easy to change. With the improvements, user does not have to check the API to figure out what each number does.
2. Fix bugs. For example one cannot use RTCP if the RTP uses consecutive ports. There were also memory leaks. I think we want to show the users how to avoid those in our examples. 
3. Check return values. Isn't user supposed to check the return values? Shouldn't we teach them to check them?
4. Make them functional. If I understood, this is the controversial part? There was some talk about adding command line parsing to examples, but I agree that this might make the examples too complicated (on the other hand, uvgRTP having a CLI might not be a bad idea). What I did was just remove infinite loops and make the examples end at some point. This did not take many code lines. There was one situation where there was just generic wait and as we discussed with testing, this does not result in a constant rate stream or any stream that makes sense in reality. I wanted to preserve the code logic so I fixed it to send at constant rate. These could maybe be implemented to send as fast as possibly, but I'm not a fan of bad code in examples.

The point about LIVE555 confuses me. Their examples don't particularly look like functional code since they select a random address to stream to. Also, I find the LIVE555 confusing because of their API, not so much because of the examples.

The branch is not yet near finish. Your comment about comprehension is something I am thinking as well and maybe something more could be done to highlight the API functions. My plan for example improvements is to merge them at the same time with C++ API and use it in the examples for simpler code (no memory management).

**Comment by altonen** [comment]
If I'm honest, I think defining the values at the beginning doesn't improve clarity that much but that's just a matter of taste. I'm not sure which bugs you're referring to but obviously those should be fixed. Checking return values is good practice, absolutely, but I intentionally left them out to make the code more readable. The whole API is Doxygen-documented, including return values and possible errors conditions, and it's easily available here on Github.

Obviously I don't know the details of internal discussions so my comment may not make sense from that point of view but let us consider, for example, `srtp_user.cc`. When I wrote that example code, my point was to show the difference between user-managed keys and ZRTP-managed keys, i.e., which lines are different (very few). Now, from my point of view, there is a lot of unnecessary code, if the point of the code is to highlight the differences. I think showing how to stream at constant 30 FPS is good for `sending.cc` but for any other example it doesn't add much value but makes the code just more verbose.

I'm not saying this is necessarily a bad direction but the direction I chose was done intentionally, and I'm saddened to see it change. I hope I'm incorrect and that this new way of showing how to use uvgRTP is better for the end-user.

**Comment by polusto** [comment]
You are looking at a work in progress, details like having too many code lines in srtp_user example are easy to fix and would have likely been fixed without this conversation. From my point of view, I did realize your intention and wanted to keep it as much as possible while also making the example such that user could also press the run button without a crash. I have seen people at least try to build the examples and using them as a basis for their code. Taking that into consideration, I think a better starting point would be something functional.

**Comment by jrsnen** [comment]
Merged the branch and also added a small tutorial. Also moved the examples to root, since they are what interest new users the most.
