### ISSUE TITLE
RFC 3550 RTCP: Modifying packet interval via context flags

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#65]
There was a suggestion by @wowaser to modify the parameters of RTCP. This could be implemented if it is not too complicated.

**Comment by wowaser** [comment]
This suggestion stems from a need to react to volatile network conditions faster than every N seconds the RTCP receiver report is received. There are some private functions that are storing the statistics with which the RTCP reports are configured. Is it possible to access that data to create the kind of system that @altonen was talking about in issue #59.
> I think you could built a better, ad-hoc session statistics gathering and distribution mechanism on top of RTP because you wouldn't have to conform to all of these, somewhat peculiar and outdated, rules

I was thinking about using the APP packets to have both sides of the stream communicate about how many packets were sent/received/lost **_after each frame_**. So, basically manually "counting" packets with existing RTCP (currently private) functionality and reacting a certain way if there is packet loss. 

Maybe you guys can give hints about which functions should be made public in order to access those statistics manually.

**Comment by polusto** [comment]
RTCP can do better than just count lost packets, it uses jitter to detect when the network condition is starting to deteriorate. From my point of view, if there was a serious issue with RTCP, there would be a new RFC to replace it. There may be some unneeded extra stuff in RTP, but it is also still very widely used which tells something.

This issue is probably easy to implement. Add new flags to those RTP_CTX_CONFIGURATION_FLAGS and then have the correct place check for the presence/value of the flag.

**Comment by altonen** [comment]
I'm not saying this has to be implement but I think what @wowaser  said still stands. I believe his criticism mainly concerns the report interval and whatever else RTCP contains that doesn't concern him. If there was a low-level interface that would allow users of uvgRTP to get the current RTCP state, they would be able to use uvgRTP to their liking even more freely, I think this would empower everyone. While I personally think this is something that uvgRTP could do, providing an alternative to the spec in order to better serve the users, such as is the case with `RCE_FRAGMENT_GENERIC`, I can understand your unwillingness to do so at least for the time being, given that there are many other issues to solve before that. I, however, agree with @polusto that this, providing low-level APIs, was not the original goal of uvgRTP.

To be honest, before my departure, I was actually thinking of implementing something similar to what @wowaser mentioned, something like `RCE_FRAGMENT_GENERIC` but for RTCP but removing all the "unnecessary" from the protocol. Just giving people access to the internal state of RTCP (# of lost packets, jitter, etc.) is easy. I think it's just a matter of gathering all of the internal RTCP state of uvgRTP under some nice struct and exposing that struct by providing a couple of functions.

I can also take a crack at this if this is just a matter of missing man hours because I also dislike RTCP  and would rather see something else, even if just an API that users could use to implement their own version of RTCP. Obviously, if whatever he's dealing with can be deal with decreasing the report interval while being compatible with other implementations, then that's obviously the best solution.

**Comment by wowaser** [comment]
>  I think it's just a matter of gathering all of the internal RTCP state of uvgRTP under some nice struct and exposing that struct by providing a couple of functions.

This is exactly what I am looking for! I think this provides much more flexibility without going too far from the original intention behind uvgRTP.  These reports would be pretty small, so sending them with each frame would barely make a scratch on the overall bandwidth. They would still be sent via RTCP tho, right?

I don't see how timed reports can be useful in a real-time application. Every 5 seconds is simply too slow, and in the worst case, we would start reacting to the problems in the network a few seconds too late. 

Thanks for the response!

**Comment by altonen** [comment]
If you use APP packets to implement the protocol then you can send them via RTCP.

I think it depends on the context. For a typical live video stream where people have stable connections over fiber, the 5 second interval could be fine because there probably wouldn't be much disturbances and thus parameters regarding the stream quality wouldn't need to be changed very often. Why the lower limit is recommended to be five seems kind of arbitrary and would probably be problematic if you were streaming in more diverse networks conditions.

**Comment by jrsnen** [comment]
I did some reading and did find that RFC 3550 does indeed allow for lower RTCP interval than 5 seconds (see https://datatracker.ietf.org/doc/html/rfc3550#section-6.2). I'm working on making improvements based on this information.

**Comment by jrsnen** [comment]
![image](https://user-images.githubusercontent.com/6498638/170989311-5b04c834-6c69-4bac-b1bc-634575bcb8f2.png)

**Comment by jrsnen** [comment]
The default interval for audio will stay the same, but will be around 100 ms for video streams. uvgRTP is also completely missing the formula for calculating the interval (I will make a new issue at some point).

**Comment by jrsnen** [comment]
I added a function that enables changing the session bandwidth. I also set a default value, which means that the RTCP interval for video is much faster.

**Comment by wowaser** [comment]
@jrsnen What function is that and what variable is responsible for the interval? Thanks

**Comment by jrsnen** [comment]
@wowaser [this](https://github.com/ultravideo/uvgRTP/blob/c451ee38d9d2627df0222b6f875040ad8c4c5b1f/include/uvgrtp/rtcp.hh#L192) modifies the session bandwidth which is used to calculate the RTCP interval. However, looking at the code, it unfortenately works in such a way that any call to this function come too late to be taken into account.

I'll reopen this issue until this is fixed. 

The modified defaults do work and they depend on the format. Audio is still 5 seconds and HEVC should be around 120 ms. Do you need smaller intervals?

**Comment by tampsa** [comment]
Fixed by 9dff5f3c586fd932f48727ac16b0f71e46deffcc and 83a7b7d0ab51dfaa0bf578295d9b55f2af3df098
