### ISSUE TITLE
Frame receiving hook with member functions

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#69]
Hi. 

This issue is similar to #43. 

Function 

```cpp
uvgrtp::media_stream::install_receive_hook(void *arg, void (*hook)(void *, uvgrtp::frame::rtp_frame *)) 
```
provides a way of pulling frames via callback function, but this doesn't work with member functions. The conversion is not provided. 

Also, which is the recommended way of getting frames, pulling in a loop, or installing a hook? Hook seems much more convenient. 

Thank you.

**Comment by wowaser** [comment]
Oh, this was already mentioned in #57.. Yikes.

**Comment by altonen** [comment]
There's really no recommended way, it just depends on your use case. Kvazzup uses hooking because of the way its filters are implemented but I've also used polling in applications that had a small and simple event loop in the main() function.

**Comment by polusto** [comment]
@wowaser It is possible to use classes with the RTP (unlike the RTCP) in current implementation. You just have to pass the class as a void parameter (arg) and then have the installed function be static where you call the converted arg->function(frame).

C++ API for this will probably come in 2.2 version of uvgRTP.

**Comment by polusto** [comment]
My view is that with hooks, there is no extra delay or CPU usage compared to pulling, but when using pulling, the code is clearer and easier to synchronize. Make the decision based on which is more important.

I'm closing this since it is already possible to use classes with current RTP API and #57 will bring the C++ API to uvgRTP.
