### ISSUE TITLE
Garbage collection for lost frames

### ISSUE THREAD

**Issue by polusto** [ultravideo/uvgRTP#74]
Currently, there is no garbage collection if a fragment of a frame is lost. This could lead to increasing memory usage over time if frames are lost on a constant basis.

This is not the same as memory leaking (#67), since the memory is not lost at any point.

Fixing this would involve finding the buffer, recording the timestamp of their reception and deleting them after some interval.

This issue was pointed out to me by @fador. I also remember @altonen talking about this at some point.

Fixing #52 first might help solve this since that is where I suspect the buffer is located?

**Comment by altonen** [comment]
This is the thing I've been talking about in multiple issues. This might even be the exact issue discussed in #67 because the definition of memory leak is not that `delete` is not called but that unused memory is not released/allocations are not handled correctly. But we have to wait more details on the referenced issue and thank you Marko for providing a simple GC implementation.

**Comment by polusto** [comment]
Implemented by b808c465c98048dfc3b67138b1e129c963d35640
